### ISSUE TITLE
sheeeps-0.3.0 crashes dedicated Forge server 1.8.9 b1764 on startup

### ISSUE THREAD

**Issue by kreezxil** [zulucap/Sheeeps#2]
Issue: sheeeps-0.3.0 crashes dedicated Forge server 1.8.9 b1764 on startup

crash report:
https://gist.github.com/0165d262e53ad6d19163

fml server latest:
https://gist.github.com/fa015d381469ebdba5e3

**Comment by zulucap** [comment]
I think I have found the solution and will be uploading a fix shortly. I've also done some additional balance tweaking and added a config option to set spawn rarity
